# Generated by Django 4.1.3 on 2022-11-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexapp', '0002_rename_team_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='pokemon_id',
        ),
        migrations.AddField(
            model_name='teams',
            name='pokemon_1_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='pokemon_2_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='pokemon_3_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='pokemon_4_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='pokemon_5_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='pokemon_6_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
