# Generated by Django 4.1.3 on 2022-11-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexapp', '0003_remove_teams_pokemon_id_teams_pokemon_1_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='equipe_id',
        ),
    ]
